### ISSUE TITLE
i have prblems with this line 

### ISSUE THREAD

**Issue by ARKopp** [BvdP/elliptical-box-maker#2]
import Inkscape_helper.inkscape_helper as doc

**Comment by BvdP** [comment]
I really should change my git workflow so that master is always releasable (currently it isnrt). I'm working on that...

Anyway, you can do two things for now. Either use the 1.0 released version (from [here](https://github.com/BvdP/elliptical-box-maker/releases))

Or you can install inkscape_helper, as is in the readme:
"You also need another extension https://github.com/BvdP/Inkscape_helper . Put the two files in a folder called "Inkscape_helper" (note the capital I) and put the folder into the extensions directory where you put the ell_box.pi and ell_box.inx files."

There is no difference in features so using the 1.0 release is the easiest option.
